import { Product, Category } from './types';

export const categories: Category[] = [
  {
    id: '1',
    name: 'Festive Collection',
    slug: 'festive',
    subcategories: [],
  },
  {
    id: '2',
    name: 'New Arrivals',
    slug: 'new-arrivals',
    subcategories: [
      { id: '2-1', name: 'Breeze Collection', slug: 'breeze-collection' },
      { id: '2-2', name: 'Rangrez Collection', slug: 'rangrez-collection' },
      { id: '2-3', name: 'Kamal Collection', slug: 'kamal-collection' },
      { id: '2-4', name: 'Utsav Collection', slug: 'utsav-collection' },
      { id: '2-5', name: 'Ikat Collection', slug: 'ikat-collection' },
      { id: '2-6', name: 'Azure Collection', slug: 'azure-collection' },
      { id: '2-7', name: 'Suram Collection', slug: 'suram-collection' },
    ],
  },
  {
    id: '3',
    name: "Women's",
    slug: 'womens',
    subcategories: [
      { id: '3-1', name: 'Dresses', slug: 'dresses' },
      { id: '3-2', name: 'Co-ord Sets', slug: 'co-ord-sets' },
      { id: '3-3', name: 'Tops', slug: 'tops' },
      { id: '3-4', name: 'Kurta Sets', slug: 'kurta-sets' },
    ],
  },
  {
    id: '4',
    name: "Men's",
    slug: 'mens',
    subcategories: [
      { id: '4-1', name: 'Shirts', slug: 'shirts' },
      { id: '4-2', name: 'Kurtas', slug: 'kurtas' },
      { id: '4-3', name: 'Checked Shirts', slug: 'checked-shirts' },
      { id: '4-4', name: 'Solid Shirts', slug: 'solid-shirts' },
      { id: '4-5', name: 'Printed Shirts', slug: 'printed-shirts' },
      { id: '4-6', name: 'Co-ord Sets', slug: 'mens-co-ord-sets' },
    ],
  },
  {
    id: '5',
    name: "Couple's",
    slug: 'couples',
    subcategories: [],
  },
  {
    id: '6',
    name: 'Jewelry',
    slug: 'jewelry',
    subcategories: [],
  },
];

export const products: Product[] = [
  // Festive Collection
  {
    id: '1',
    name: 'Festive Silk Saree',
    description: 'Elegant silk saree perfect for festive occasions. Features intricate embroidery and rich colors.',
    price: 4999,
    originalPrice: 6999,
    discount: 29,
    images: [
      'https://images.unsplash.com/photo-1610030469983-98e550d6193c?w=500&h=500&fit=crop',
      'https://images.unsplash.com/photo-1583391733956-3750e0ff4e8b?w=500&h=500&fit=crop',
    ],
    category: 'Festive Collection',
    subcategory: '',
    brand: 'FestiveWear',
    rating: 4.9,
    reviewCount: 234,
    inStock: true,
    stockCount: 15,
    colors: ['Red', 'Maroon', 'Gold'],
    sizes: ['Free Size'],
    featured: true,
    bestSeller: true,
  },
  {
    id: '2',
    name: 'Embroidered Kurta Set',
    description: 'Beautifully embroidered kurta set for festive celebrations. Premium fabric with traditional designs.',
    price: 2999,
    originalPrice: 3999,
    discount: 25,
    images: [
      'https://images.unsplash.com/photo-1594938298603-c8148c4dae35?w=500&h=500&fit=crop',
      'https://images.unsplash.com/photo-1583391733956-3750e0ff4e8b?w=500&h=500&fit=crop',
    ],
    category: 'Festive Collection',
    subcategory: '',
    brand: 'FestiveWear',
    rating: 4.8,
    reviewCount: 189,
    inStock: true,
    stockCount: 22,
    colors: ['Cream', 'Navy', 'Burgundy'],
    sizes: ['S', 'M', 'L', 'XL'],
    featured: true,
  },
  // New Arrivals - Breeze Collection
  {
    id: '3',
    name: 'Breeze Floral Dress',
    description: 'Light and breezy floral dress perfect for summer days. Breathable fabric with beautiful prints.',
    price: 1999,
    originalPrice: 2499,
    discount: 20,
    images: [
      'https://images.unsplash.com/photo-1572804013309-59a88b7e92f1?w=500&h=500&fit=crop',
      'https://images.unsplash.com/photo-1515372039744-b8f02a3ae446?w=500&h=500&fit=crop',
    ],
    category: 'New Arrivals',
    subcategory: 'Breeze Collection',
    brand: 'Breeze',
    rating: 4.7,
    reviewCount: 156,
    inStock: true,
    stockCount: 28,
    colors: ['Pink Floral', 'Blue Floral', 'Yellow Floral'],
    sizes: ['XS', 'S', 'M', 'L', 'XL'],
    featured: true,
    newArrival: true,
  },
  {
    id: '4',
    name: 'Breeze Cotton Top',
    description: 'Soft cotton top with delicate embroidery. Perfect for casual outings.',
    price: 899,
    originalPrice: 1199,
    discount: 25,
    images: [
      'https://images.unsplash.com/photo-1434389677669-e08b4cac3105?w=500&h=500&fit=crop',
      'https://images.unsplash.com/photo-1485462537746-965f33f7f6a7?w=500&h=500&fit=crop',
    ],
    category: 'New Arrivals',
    subcategory: 'Breeze Collection',
    brand: 'Breeze',
    rating: 4.6,
    reviewCount: 98,
    inStock: true,
    stockCount: 35,
    colors: ['White', 'Peach', 'Mint'],
    sizes: ['S', 'M', 'L', 'XL'],
    featured: true,
    newArrival: true,
  },
  // New Arrivals - Rangrez Collection
  {
    id: '5',
    name: 'Rangrez Printed Kurta',
    description: 'Vibrant printed kurta inspired by traditional Rangrez art. Bold colors and unique patterns.',
    price: 1599,
    originalPrice: 1999,
    discount: 20,
    images: [
      'https://images.unsplash.com/photo-1594938298603-c8148c4dae35?w=500&h=500&fit=crop',
      'https://images.unsplash.com/photo-1583391733956-3750e0ff4e8b?w=500&h=500&fit=crop',
    ],
    category: 'New Arrivals',
    subcategory: 'Rangrez Collection',
    brand: 'Rangrez',
    rating: 4.8,
    reviewCount: 145,
    inStock: true,
    stockCount: 20,
    colors: ['Multi-color', 'Blue-Gold', 'Red-Silver'],
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
    featured: true,
    newArrival: true,
  },
  // New Arrivals - Kamal Collection
  {
    id: '6',
    name: 'Kamal Lotus Dress',
    description: 'Elegant dress featuring lotus-inspired prints. Sophisticated design for special occasions.',
    price: 2499,
    originalPrice: 3199,
    discount: 22,
    images: [
      'https://images.unsplash.com/photo-1572804013309-59a88b7e92f1?w=500&h=500&fit=crop',
      'https://images.unsplash.com/photo-1515372039744-b8f02a3ae446?w=500&h=500&fit=crop',
    ],
    category: 'New Arrivals',
    subcategory: 'Kamal Collection',
    brand: 'Kamal',
    rating: 4.9,
    reviewCount: 112,
    inStock: true,
    stockCount: 18,
    colors: ['Pink', 'Purple', 'White'],
    sizes: ['XS', 'S', 'M', 'L'],
    featured: true,
    newArrival: true,
  },
  // New Arrivals - Utsav Collection
  {
    id: '6a',
    name: 'Utsav Festive Lehenga',
    description: 'Beautiful lehenga with intricate embroidery and rich colors. Perfect for celebrations.',
    price: 5999,
    originalPrice: 7999,
    discount: 25,
    images: [
      'https://images.unsplash.com/photo-1610030469983-98e550d6193c?w=500&h=500&fit=crop',
      'https://images.unsplash.com/photo-1583391733956-3750e0ff4e8b?w=500&h=500&fit=crop',
    ],
    category: 'New Arrivals',
    subcategory: 'Utsav Collection',
    brand: 'Utsav',
    rating: 4.8,
    reviewCount: 145,
    inStock: true,
    stockCount: 14,
    colors: ['Red', 'Maroon', 'Gold'],
    sizes: ['S', 'M', 'L'],
    featured: true,
    newArrival: true,
  },
  {
    id: '6b',
    name: 'Utsav Celebration Saree',
    description: 'Elegant saree with traditional patterns and modern styling. Perfect for festive occasions.',
    price: 4499,
    originalPrice: 5999,
    discount: 25,
    images: [
      'https://images.unsplash.com/photo-1583391733956-3750e0ff4e8b?w=500&h=500&fit=crop',
      'https://images.unsplash.com/photo-1610030469983-98e550d6193c?w=500&h=500&fit=crop',
    ],
    category: 'New Arrivals',
    subcategory: 'Utsav Collection',
    brand: 'Utsav',
    rating: 4.9,
    reviewCount: 178,
    inStock: true,
    stockCount: 20,
    colors: ['Purple', 'Pink', 'Blue'],
    sizes: ['Free Size'],
    featured: true,
    newArrival: true,
  },
  // Women's - Dresses
  {
    id: '7',
    name: 'Elegant Evening Dress',
    description: 'Stunning evening dress for special occasions. Flowing fabric with elegant silhouette.',
    price: 3299,
    originalPrice: 4299,
    discount: 23,
    images: [
      'https://images.unsplash.com/photo-1572804013309-59a88b7e92f1?w=500&h=500&fit=crop',
      'https://images.unsplash.com/photo-1515372039744-b8f02a3ae446?w=500&h=500&fit=crop',
    ],
    category: "Women's",
    subcategory: 'Dresses',
    brand: 'Elegance',
    rating: 4.8,
    reviewCount: 267,
    inStock: true,
    stockCount: 24,
    colors: ['Black', 'Navy', 'Emerald'],
    sizes: ['XS', 'S', 'M', 'L', 'XL'],
    featured: true,
    bestSeller: true,
  },
  {
    id: '8',
    name: 'Casual Day Dress',
    description: 'Comfortable casual dress perfect for everyday wear. Soft fabric with flattering fit.',
    price: 1499,
    originalPrice: 1999,
    discount: 25,
    images: [
      'https://images.unsplash.com/photo-1572804013309-59a88b7e92f1?w=500&h=500&fit=crop',
      'https://images.unsplash.com/photo-1515372039744-b8f02a3ae446?w=500&h=500&fit=crop',
    ],
    category: "Women's",
    subcategory: 'Dresses',
    brand: 'CasualWear',
    rating: 4.6,
    reviewCount: 198,
    inStock: true,
    stockCount: 32,
    colors: ['Blue', 'Pink', 'Yellow'],
    sizes: ['S', 'M', 'L', 'XL'],
    featured: true,
  },
  // Women's - Co-ord Sets
  {
    id: '9',
    name: 'Floral Co-ord Set',
    description: 'Trendy co-ord set with beautiful floral print. Perfect for brunch and casual outings.',
    price: 2199,
    originalPrice: 2799,
    discount: 21,
    images: [
      'https://images.unsplash.com/photo-1515372039744-b8f02a3ae446?w=500&h=500&fit=crop',
      'https://images.unsplash.com/photo-1434389677669-e08b4cac3105?w=500&h=500&fit=crop',
    ],
    category: "Women's",
    subcategory: 'Co-ord Sets',
    brand: 'Trendy',
    rating: 4.7,
    reviewCount: 156,
    inStock: true,
    stockCount: 19,
    colors: ['Floral Pink', 'Floral Blue', 'Floral Yellow'],
    sizes: ['S', 'M', 'L'],
    featured: true,
    newArrival: true,
  },
  // Women's - Tops
  {
    id: '10',
    name: 'Embroidered Top',
    description: 'Beautiful embroidered top with delicate details. Perfect for both casual and formal occasions.',
    price: 1299,
    originalPrice: 1699,
    discount: 24,
    images: [
      'https://images.unsplash.com/photo-1434389677669-e08b4cac3105?w=500&h=500&fit=crop',
      'https://images.unsplash.com/photo-1485462537746-965f33f7f6a7?w=500&h=500&fit=crop',
    ],
    category: "Women's",
    subcategory: 'Tops',
    brand: 'ElegantTops',
    rating: 4.5,
    reviewCount: 134,
    inStock: true,
    stockCount: 28,
    colors: ['White', 'Cream', 'Peach'],
    sizes: ['S', 'M', 'L', 'XL'],
    featured: true,
  },
  // Women's - Kurta Sets
  {
    id: '11',
    name: 'Traditional Kurta Set',
    description: 'Classic kurta set with intricate embroidery. Perfect for festivals and celebrations.',
    price: 2499,
    originalPrice: 3199,
    discount: 22,
    images: [
      'https://images.unsplash.com/photo-1594938298603-c8148c4dae35?w=500&h=500&fit=crop',
      'https://images.unsplash.com/photo-1583391733956-3750e0ff4e8b?w=500&h=500&fit=crop',
    ],
    category: "Women's",
    subcategory: 'Kurta Sets',
    brand: 'Traditional',
    rating: 4.9,
    reviewCount: 223,
    inStock: true,
    stockCount: 16,
    colors: ['Maroon', 'Navy', 'Green'],
    sizes: ['S', 'M', 'L', 'XL'],
    featured: true,
    bestSeller: true,
  },
  // Men's - Shirts
  {
    id: '12',
    name: 'Classic Formal Shirt',
    description: 'Premium formal shirt perfect for office and formal events. Crisp fabric with perfect fit.',
    price: 1799,
    originalPrice: 2299,
    discount: 22,
    images: [
      'https://images.unsplash.com/photo-1602810318383-e386cc2a3ccf?w=500&h=500&fit=crop',
      'https://images.unsplash.com/photo-1596755094514-f87e34085b2c?w=500&h=500&fit=crop',
    ],
    category: "Men's",
    subcategory: 'Shirts',
    brand: 'FormalWear',
    rating: 4.7,
    reviewCount: 289,
    inStock: true,
    stockCount: 35,
    colors: ['White', 'Light Blue', 'Pink'],
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
    featured: true,
    bestSeller: true,
  },
  // Men's - Kurtas
  {
    id: '13',
    name: 'Embroidered Kurta',
    description: 'Elegant kurta with beautiful embroidery. Perfect for festive occasions.',
    price: 1999,
    originalPrice: 2599,
    discount: 23,
    images: [
      'https://images.unsplash.com/photo-1594938298603-c8148c4dae35?w=500&h=500&fit=crop',
      'https://images.unsplash.com/photo-1583391733956-3750e0ff4e8b?w=500&h=500&fit=crop',
    ],
    category: "Men's",
    subcategory: 'Kurtas',
    brand: 'EthnicWear',
    rating: 4.8,
    reviewCount: 198,
    inStock: true,
    stockCount: 22,
    colors: ['Cream', 'Navy', 'Maroon'],
    sizes: ['S', 'M', 'L', 'XL'],
    featured: true,
  },
  // Men's - Checked Shirts
  {
    id: '14',
    name: 'Checked Casual Shirt',
    description: 'Stylish checked shirt perfect for casual outings. Comfortable fabric with modern design.',
    price: 1499,
    originalPrice: 1899,
    discount: 21,
    images: [
      'https://images.unsplash.com/photo-1596755094514-f87e34085b2c?w=500&h=500&fit=crop',
      'https://images.unsplash.com/photo-1602810318383-e386cc2a3ccf?w=500&h=500&fit=crop',
    ],
    category: "Men's",
    subcategory: 'Checked Shirts',
    brand: 'CasualWear',
    rating: 4.6,
    reviewCount: 156,
    inStock: true,
    stockCount: 28,
    colors: ['Blue-White', 'Red-Black', 'Green-White'],
    sizes: ['S', 'M', 'L', 'XL'],
    featured: true,
  },
  // Men's - Solid Shirts
  {
    id: '15',
    name: 'Solid Color Shirt',
    description: 'Versatile solid color shirt for any occasion. Premium fabric with excellent fit.',
    price: 1299,
    originalPrice: 1699,
    discount: 24,
    images: [
      'https://images.unsplash.com/photo-1602810318383-e386cc2a3ccf?w=500&h=500&fit=crop',
      'https://images.unsplash.com/photo-1596755094514-f87e34085b2c?w=500&h=500&fit=crop',
    ],
    category: "Men's",
    subcategory: 'Solid Shirts',
    brand: 'Essential',
    rating: 4.5,
    reviewCount: 189,
    inStock: true,
    stockCount: 32,
    colors: ['White', 'Black', 'Navy', 'Grey'],
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
    featured: true,
  },
  // Men's - Printed Shirts
  {
    id: '16',
    name: 'Printed Casual Shirt',
    description: 'Trendy printed shirt with unique patterns. Perfect for casual outings.',
    price: 1399,
    originalPrice: 1799,
    discount: 22,
    images: [
      'https://images.unsplash.com/photo-1596755094514-f87e34085b2c?w=500&h=500&fit=crop',
      'https://images.unsplash.com/photo-1602810318383-e386cc2a3ccf?w=500&h=500&fit=crop',
    ],
    category: "Men's",
    subcategory: 'Printed Shirts',
    brand: 'Trendy',
    rating: 4.7,
    reviewCount: 134,
    inStock: true,
    stockCount: 24,
    colors: ['Floral', 'Geometric', 'Abstract'],
    sizes: ['S', 'M', 'L', 'XL'],
    featured: true,
    newArrival: true,
  },
  // Men's - Co-ord Sets
  {
    id: '17',
    name: 'Men Co-ord Set',
    description: 'Stylish co-ord set for men. Perfect for casual outings and parties.',
    price: 2499,
    originalPrice: 3199,
    discount: 22,
    images: [
      'https://images.unsplash.com/photo-1594938298603-c8148c4dae35?w=500&h=500&fit=crop',
      'https://images.unsplash.com/photo-1583391733956-3750e0ff4e8b?w=500&h=500&fit=crop',
    ],
    category: "Men's",
    subcategory: 'Co-ord Sets',
    brand: 'Modern',
    rating: 4.8,
    reviewCount: 112,
    inStock: true,
    stockCount: 18,
    colors: ['Navy', 'Black', 'Grey'],
    sizes: ['S', 'M', 'L', 'XL'],
    featured: true,
    newArrival: true,
  },
  // Couple's
  {
    id: '18',
    name: 'Matching Couple Set',
    description: 'Beautiful matching outfit for couples. Perfect for special occasions and celebrations.',
    price: 5999,
    originalPrice: 7999,
    discount: 25,
    images: [
      'https://images.unsplash.com/photo-1594938298603-c8148c4dae35?w=500&h=500&fit=crop',
      'https://images.unsplash.com/photo-1572804013309-59a88b7e92f1?w=500&h=500&fit=crop',
    ],
    category: "Couple's",
    subcategory: '',
    brand: 'CoupleWear',
    rating: 4.9,
    reviewCount: 89,
    inStock: true,
    stockCount: 12,
    colors: ['Maroon-Gold', 'Navy-Silver', 'Black-Red'],
    sizes: ['S', 'M', 'L', 'XL'],
    featured: true,
    bestSeller: true,
  },
  // Jewelry
  {
    id: '19',
    name: 'Gold Pendant Necklace',
    description: 'Elegant gold pendant necklace with intricate design. Perfect for special occasions.',
    price: 8999,
    originalPrice: 11999,
    discount: 25,
    images: [
      'https://images.unsplash.com/photo-1599643478518-a784e5dc4c8f?w=500&h=500&fit=crop',
      'https://images.unsplash.com/photo-1601121141461-9d6647bca1ed?w=500&h=500&fit=crop',
    ],
    category: 'Jewelry',
    subcategory: '',
    brand: 'LuxuryJewels',
    rating: 4.9,
    reviewCount: 167,
    inStock: true,
    stockCount: 8,
    colors: ['Gold', 'Rose Gold'],
    featured: true,
    bestSeller: true,
  },
  {
    id: '20',
    name: 'Diamond Stud Earrings',
    description: 'Stunning diamond stud earrings. Perfect for everyday wear and special occasions.',
    price: 12999,
    originalPrice: 15999,
    discount: 19,
    images: [
      'https://images.unsplash.com/photo-1535632066927-ab7c9ab60908?w=500&h=500&fit=crop',
      'https://images.unsplash.com/photo-1601121141461-9d6647bca1ed?w=500&h=500&fit=crop',
    ],
    category: 'Jewelry',
    subcategory: '',
    brand: 'LuxuryJewels',
    rating: 5.0,
    reviewCount: 234,
    inStock: true,
    stockCount: 6,
    colors: ['White Gold', 'Yellow Gold'],
    featured: true,
  },
];
