import { Product, Category } from './types';

export const categories: Category[] = [
  {
    id: '1',
    name: 'Electronics',
    slug: 'electronics',
    subcategories: [
      { id: '1-1', name: 'Phones', slug: 'phones' },
      { id: '1-2', name: 'Laptops', slug: 'laptops' },
      { id: '1-3', name: 'Tablets', slug: 'tablets' },
      { id: '1-4', name: 'Accessories', slug: 'accessories' },
    ],
  },
  {
    id: '2',
    name: 'Fashion',
    slug: 'fashion',
    subcategories: [
      { id: '2-1', name: 'Men', slug: 'men' },
      { id: '2-2', name: 'Women', slug: 'women' },
      { id: '2-3', name: 'Kids', slug: 'kids' },
      { id: '2-4', name: 'Accessories', slug: 'accessories' },
    ],
  },
  {
    id: '3',
    name: 'Home & Living',
    slug: 'home-living',
    subcategories: [
      { id: '3-1', name: 'Furniture', slug: 'furniture' },
      { id: '3-2', name: 'Decor', slug: 'decor' },
      { id: '3-3', name: 'Kitchen', slug: 'kitchen' },
    ],
  },
  {
    id: '4',
    name: 'Sports',
    slug: 'sports',
    subcategories: [
      { id: '4-1', name: 'Equipment', slug: 'equipment' },
      { id: '4-2', name: 'Clothing', slug: 'clothing' },
      { id: '4-3', name: 'Footwear', slug: 'footwear' },
    ],
  },
];

export const products: Product[] = [
  {
    id: '1',
    name: 'Premium Wireless Headphones',
    description: 'Experience crystal-clear audio with our premium wireless headphones. Featuring active noise cancellation, 30-hour battery life, and ultra-comfortable ear cushions for all-day listening.',
    price: 299.99,
    originalPrice: 399.99,
    discount: 25,
    images: [
      'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=500&h=500&fit=crop',
      'https://images.unsplash.com/photo-1484704849700-f032a568e944?w=500&h=500&fit=crop',
    ],
    category: 'Electronics',
    subcategory: 'Accessories',
    brand: 'AudioTech',
    rating: 4.8,
    reviewCount: 1250,
    inStock: true,
    stockCount: 45,
    colors: ['Black', 'White', 'Silver'],
    featured: true,
    bestSeller: true,
  },
  {
    id: '2',
    name: 'Smart Watch Pro',
    description: 'Stay connected and track your fitness with our advanced smartwatch. Features include heart rate monitoring, GPS, water resistance, and a stunning AMOLED display.',
    price: 449.99,
    originalPrice: 549.99,
    discount: 18,
    images: [
      'https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=500&h=500&fit=crop',
      'https://images.unsplash.com/photo-1546868871-7041f2a55e12?w=500&h=500&fit=crop',
    ],
    category: 'Electronics',
    subcategory: 'Accessories',
    brand: 'TechFit',
    rating: 4.7,
    reviewCount: 890,
    inStock: true,
    stockCount: 32,
    colors: ['Black', 'Silver', 'Rose Gold'],
    featured: true,
    newArrival: true,
  },
  {
    id: '3',
    name: 'Classic Leather Jacket',
    description: 'Timeless style meets modern comfort. This premium leather jacket features genuine leather, quilted lining, and a perfect fit for any occasion.',
    price: 249.99,
    originalPrice: 349.99,
    discount: 29,
    images: [
      'https://images.unsplash.com/photo-1551028719-00167b16eac5?w=500&h=500&fit=crop',
      'https://images.unsplash.com/photo-1520975954732-35dd22299614?w=500&h=500&fit=crop',
    ],
    category: 'Fashion',
    subcategory: 'Men',
    brand: 'LeatherLux',
    rating: 4.9,
    reviewCount: 567,
    inStock: true,
    stockCount: 18,
    colors: ['Black', 'Brown', 'Tan'],
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
    featured: true,
    bestSeller: true,
  },
  {
    id: '4',
    name: 'Running Shoes Elite',
    description: 'Engineered for performance, these running shoes feature advanced cushioning, breathable mesh, and a lightweight design for maximum comfort.',
    price: 179.99,
    originalPrice: 229.99,
    discount: 22,
    images: [
      'https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=500&h=500&fit=crop',
      'https://images.unsplash.com/photo-1460353581641-37baddab0fa2?w=500&h=500&fit=crop',
    ],
    category: 'Sports',
    subcategory: 'Footwear',
    brand: 'SpeedRun',
    rating: 4.6,
    reviewCount: 1243,
    inStock: true,
    stockCount: 67,
    colors: ['Black/Red', 'White/Blue', 'Gray/Yellow'],
    sizes: ['7', '8', '9', '10', '11', '12'],
    featured: true,
  },
  {
    id: '5',
    name: 'Minimalist Desk Lamp',
    description: 'Add style and functionality to your workspace with this sleek LED desk lamp. Adjustable brightness, color temperature control, and USB charging port.',
    price: 89.99,
    originalPrice: 119.99,
    discount: 25,
    images: [
      'https://images.unsplash.com/photo-1507473885765-e6ed057f782c?w=500&h=500&fit=crop',
      'https://images.unsplash.com/photo-1513506003011-3b03c801e992?w=500&h=500&fit=crop',
    ],
    category: 'Home & Living',
    subcategory: 'Decor',
    brand: 'Lumina',
    rating: 4.5,
    reviewCount: 432,
    inStock: true,
    stockCount: 89,
    colors: ['White', 'Black', 'Gold'],
    featured: true,
    newArrival: true,
  },
  {
    id: '6',
    name: 'Professional Camera Kit',
    description: 'Capture every moment in stunning detail with this professional camera kit. Includes camera body, versatile lens, and essential accessories.',
    price: 1299.99,
    originalPrice: 1599.99,
    discount: 19,
    images: [
      'https://images.unsplash.com/photo-1516035069371-29a1b244cc32?w=500&h=500&fit=crop',
      'https://images.unsplash.com/photo-1502920917128-1aa500764cbd?w=500&h=500&fit=crop',
    ],
    category: 'Electronics',
    subcategory: 'Accessories',
    brand: 'PhotoPro',
    rating: 4.9,
    reviewCount: 789,
    inStock: true,
    stockCount: 12,
    colors: ['Black'],
    featured: true,
    bestSeller: true,
  },
  {
    id: '7',
    name: 'Elegant Summer Dress',
    description: 'Perfect for warm weather, this elegant summer dress features lightweight fabric, flattering silhouette, and beautiful floral patterns.',
    price: 129.99,
    originalPrice: 179.99,
    discount: 28,
    images: [
      'https://images.unsplash.com/photo-1572804013309-59a88b7e92f1?w=500&h=500&fit=crop',
      'https://images.unsplash.com/photo-1515372039744-b8f02a3ae446?w=500&h=500&fit=crop',
    ],
    category: 'Fashion',
    subcategory: 'Women',
    brand: 'Elegance',
    rating: 4.7,
    reviewCount: 654,
    inStock: true,
    stockCount: 34,
    colors: ['Floral', 'Solid Blue', 'Solid Pink'],
    sizes: ['XS', 'S', 'M', 'L', 'XL'],
    featured: true,
    newArrival: true,
  },
  {
    id: '8',
    name: 'Modern Coffee Table',
    description: 'Transform your living room with this modern coffee table. Features sleek design, sturdy construction, and ample storage space.',
    price: 349.99,
    originalPrice: 449.99,
    discount: 22,
    images: [
      'https://images.unsplash.com/photo-1532372320572-cda25653a26d?w=500&h=500&fit=crop',
      'https://images.unsplash.com/photo-1533090481720-856c6e3c1fdc?w=500&h=500&fit=crop',
    ],
    category: 'Home & Living',
    subcategory: 'Furniture',
    brand: 'ModernHome',
    rating: 4.6,
    reviewCount: 321,
    inStock: true,
    stockCount: 23,
    colors: ['Oak', 'Walnut', 'White'],
    featured: true,
  },
  {
    id: '9',
    name: 'Yoga Mat Premium',
    description: 'Elevate your yoga practice with this premium non-slip yoga mat. Extra thick for comfort, eco-friendly materials, and carrying strap included.',
    price: 59.99,
    originalPrice: 79.99,
    discount: 25,
    images: [
      'https://images.unsplash.com/photo-1601925260368-ae2f83cf8b7f?w=500&h=500&fit=crop',
      'https://images.unsplash.com/photo-1544367567-0f2fcb009e0b?w=500&h=500&fit=crop',
    ],
    category: 'Sports',
    subcategory: 'Equipment',
    brand: 'YogaPro',
    rating: 4.8,
    reviewCount: 987,
    inStock: true,
    stockCount: 156,
    colors: ['Purple', 'Blue', 'Green', 'Black'],
    featured: true,
    bestSeller: true,
  },
  {
    id: '10',
    name: 'Wireless Earbuds Pro',
    description: 'Immerse yourself in music with these premium wireless earbuds. Active noise cancellation, transparency mode, and 24-hour battery life.',
    price: 199.99,
    originalPrice: 249.99,
    discount: 20,
    images: [
      'https://images.unsplash.com/photo-1590658268037-6bf12165a8df?w=500&h=500&fit=crop',
      'https://images.unsplash.com/photo-1606220588913-b3aacb4d2f46?w=500&h=500&fit=crop',
    ],
    category: 'Electronics',
    subcategory: 'Accessories',
    brand: 'AudioTech',
    rating: 4.7,
    reviewCount: 1456,
    inStock: true,
    stockCount: 78,
    colors: ['Black', 'White'],
    featured: true,
    newArrival: true,
  },
  {
    id: '11',
    name: 'Designer Sunglasses',
    description: 'Make a statement with these designer sunglasses. UV protection, polarized lenses, and a timeless design that never goes out of style.',
    price: 189.99,
    originalPrice: 249.99,
    discount: 24,
    images: [
      'https://images.unsplash.com/photo-1572635196237-14b3f281503f?w=500&h=500&fit=crop',
      'https://images.unsplash.com/photo-1511499767150-a48a237f0083?w=500&h=500&fit=crop',
    ],
    category: 'Fashion',
    subcategory: 'Accessories',
    brand: 'SunStyle',
    rating: 4.5,
    reviewCount: 543,
    inStock: true,
    stockCount: 45,
    colors: ['Black', 'Tortoise', 'Clear'],
    featured: true,
  },
  {
    id: '12',
    name: 'Smart Home Speaker',
    description: 'Control your home with voice commands using this smart speaker. Premium sound quality, built-in voice assistant, and multi-room audio.',
    price: 149.99,
    originalPrice: 199.99,
    discount: 25,
    images: [
      'https://images.unsplash.com/photo-1589492477829-5e65395b66cc?w=500&h=500&fit=crop',
      'https://images.unsplash.com/photo-1558089687-f282ffcbc126?w=500&h=500&fit=crop',
    ],
    category: 'Electronics',
    subcategory: 'Accessories',
    brand: 'SmartAudio',
    rating: 4.6,
    reviewCount: 876,
    inStock: true,
    stockCount: 56,
    colors: ['Charcoal', 'Chalk', 'Coral'],
    featured: true,
    bestSeller: true,
  },
];
